name: React Native CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Run ESLint
        run: yarn lint

      - name: Run Jest Tests
        run: yarn test --ci --coverage

      - name: Cache Gradle Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/*.gradle.kts*') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Build Android App
        run: cd android && ./gradlew assembleDebug

      - name: Upload Android APK
        uses: actions/upload-artifact@v4
        with:
          name: android-app
          path: android/app/build/outputs/apk/debug/app-debug.apk

  ios-build:
    name: Build iOS App
    runs-on: macos-latest
    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Install CocoaPods
        run: cd ios && pod install --quiet

      - name: Build iOS App
        run: cd ios && xcodebuild -workspace mobileapp.xcworkspace -scheme mobileapp -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest' build

      - name: Upload iOS Build
        uses: actions/upload-artifact@v4
        with:
          name: ios-app
          path: ios/build/Debug-iphonesimulator/*.app
