name: React Native CI/CD

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  android-build:
    name: Build Android App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache Yarn dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/yarn
            **/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('mobileapp/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        run: |
          cd mobileapp
          yarn install --frozen-lockfile

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Grant Permission to Gradlew
        run: |
          cd mobileapp/android
          chmod +x gradlew

      - name: Build Android APK
        run: |
          cd mobileapp/android
          ./gradlew assembleRelease

      - name: Upload Android APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: mobileapp/android/app/build/outputs/apk/release/app-release.apk

  ios-build:
    name: Build iOS App
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache Yarn dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/yarn
            **/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('mobileapp/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        run: |
          cd mobileapp
          yarn install --frozen-lockfile

      - name: Install CocoaPods
        run: |
          cd mobileapp/ios
          pod install --repo-update

      - name: Build iOS App
        run: |
          cd mobileapp/ios
          xcodebuild -workspace mobileapp.xcworkspace \
                     -scheme mobileapp \
                     -sdk iphoneos \
                     -configuration Release \
                     -archivePath $PWD/build/mobileapp.xcarchive \
                     archive

      - name: Export iOS IPA
        run: |
          cd mobileapp/ios
          xcodebuild -exportArchive \
                     -archivePath $PWD/build/mobileapp.xcarchive \
                     -exportOptionsPlist exportOptions.plist \
                     -exportPath $PWD/build

      - name: Upload iOS IPA
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: mobileapp/ios/build/mobileapp.ipa
