name: React Native CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allows manual triggers

jobs:
  android:
    name: Android Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Install dependencies
        run: |
          cd mobileapp
          yarn install --frozen-lockfile

      - name: Run ESLint
        run: |
          cd mobileapp
          yarn lint

      - name: Run Jest tests
        run: |
          cd mobileapp
          yarn test

      - name: Set up Java & Gradle
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Build Android App
        run: |
          cd mobileapp/android
          chmod +x gradlew
          ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: android-apk
          path: mobileapp/android/app/build/outputs/apk/release/app-release.apk

  ios:
    name: iOS Build
    runs-on: macos-latest
    needs: android

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Install dependencies
        run: |
          cd mobileapp
          yarn install --frozen-lockfile

      - name: Install CocoaPods
        run: |
          cd mobileapp/ios
          pod install --silent

      - name: Build iOS App
        run: |
          cd mobileapp/ios
          xcodebuild -workspace YourApp.xcworkspace \
            -scheme YourApp \
            -sdk iphoneos \
            -configuration Release \
            archive -archivePath build/YourApp.xcarchive

      - name: Export IPA
        run: |
          cd mobileapp/ios
          xcodebuild -exportArchive \
            -archivePath build/YourApp.xcarchive \
            -exportOptionsPlist exportOptions.plist \
            -exportPath build

      - name: Upload IPA
        uses: actions/upload-artifact@v3
        with:
          name: ios-ipa
          path: mobileapp/ios/build/YourApp.ipa
